[package]
name = "esrtool"
version = "0.1.0"
edition = "2021"
authors = 
description = 
readme = "README.md"
homepage = "https://github.com/ali-raheem/esrtool_rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
